****   This program simply tests that the derivatives
****   of the Lagrangian of order 4 found by Maple
****   are correct (or better, were correctly edited back into FORM).
****   The solutions are read from the file f4ord.frm
****   and the previous output of the FORM program 2-Lagr3dim.frm
****   is read from all.sav (generated by 2-Lagr3dim.frm)

CFunctions f,D,diff,mu,la,B,nB,dB,U;
Symbols xx,a,b,c,i,j,k,[1/Hess],[Hess],[1/f(2*b)];
load all.sav;
.sort

L aaa=all;
Brackets mu,la;
.sort

#include- f4ord.frm;
.sort

skip;
nskip aaa;
#do i ={f(4*a),f(4*b),f(4*c),f(3*a+b),f(3*a+c),f(3*b+a),f(3*b+c),f(3*c+a),f(3*c+b),f(2*a+2*b),f(2*b+2*c),f(2*a+2*c),f(2*a+b+c),f(2*b+a+c),f(2*c+b+a)}
 id `i'=[`i'];
#enddo
.sort

skip;
nskip aaa;
repeat; 
id [Hess]*[1/Hess]=1;
id f(a + b)^2*f(2*c) = -( - f(2*a)*f(2*b)*f(2*c) + f(2*b)*f(a + c)^2
     - 2*f(a + b)*f(a + c)*f(b + c) + f(2*a)*f(b + c)^2) - [Hess];
id f(2*b)*[1/f(2*b)]=1;
endrepeat;
print aaa;
.end

repeat; 
id [Hess]*[1/Hess]=1;
id f(a + b)^2*f(2*c) = -( - f(2*a)*f(2*b)*f(2*c) + f(2*b)*f(a + c)^2
     - 2*f(a + b)*f(a + c)*f(b + c) + f(2*a)*f(b + c)^2) - [Hess];
id f(2*b)*[1/f(2*b)]=1;
endrepeat;
