# ============================================================================
# atkG_n2_decision.py -- THEOREM G in TWO variables: COMPLETE exact decision
# over ALL polynomials of degree <= 5 (linear terms included), agent key atkG.
#
# STATEMENT DECIDED.  For every e in C[x1,x2] with deg e <= 5:
#       B(e) := grad(e)^T adj(Hess e) grad(e) == 0   ==>   det Hess e == 0,
# and in fact e in C[x2] after a linear change (the sharper Corollary).
#
# WHY A NEW SCRIPT.  The existing n = 2 certificates do not settle degrees 4
# and 5 over the full coefficient space:
#   * theorem_G_n2_elementary.py drops linear terms (found by pzG);
#   * pzG_n2_decision.py decides degrees 2, 3 but its recorded output
#     (pzG_n2_decision.out.txt) STOPS at the degree-4 header -- the 14-variable
#     Groebner basis never finished on disk;
#   * theorem_G_n2_deg45.py "TEST 2" parametrises ONLY THE TOP FORM
#     (e = x2^d + sum_j c_j x1^{d-j} x2^j is HOMOGENEOUS), where the theorem is
#     a one-liner by Identity E; its "complete decision on a normalised slice"
#     therefore does not cover inhomogeneous e at all.
# This script covers everything of degree <= 5 by first proving a
# normalisation and then running Groebner/radical-membership on the
# normalised (still complete) slice.
#
# NORMALISATION (each step certified below):
#   (N1) B is affine-covariant: B(e o A) = det(A)^2 * B(e) o A for linear A
#        (fully symbolic, generic cubic) and B(e o tau) = B(e) o tau for
#        translations (B is built from derivatives).  det Hess is likewise
#        covariant.  Adding a constant to e changes nothing.
#   (N2) Top-degree piece: [B(e)]_{5d-7} = B(e_d) = (d/(d-1)) e_d det Hess e_d
#        (Identity E, certified for binary forms d = 2..5).  So B == 0 and
#        deg e = d >= 2 force det Hess(e_d) == 0.
#   (N3) A binary form of degree d with det Hess == 0 is c * l^d for a linear
#        form l: certified for d = 2..5 by radical membership -- every 2x2
#        minor of the Hankel matrix of e_d (whose vanishing is equivalent to
#        e_d being a d-th power) lies in the radical of the ideal of the
#        coefficients of det Hess(e_d).
#   Hence, by (N1)-(N3), every e of degree d with B == 0 is, after a linear
#   change, scaling of e and dropping the constant term,
#        e = x2^d + (arbitrary terms of degree 1..d-1).                 (S_d)
#   The slice (S_d) is COMPLETE for degree exactly d; degrees < d are covered
#   by the runs for smaller d (d = 1 is trivial: Hess = 0).
# DECISION on (S_d), d = 2..5: Groebner basis of the ideal I_d generated by
#   the x-coefficients of B(e); then (a) every x-coefficient of det Hess e and
#   (b) every coefficient of e on a monomial involving x1 is certified to lie
#   in rad(I_d) (power reduction, else Rabinowitsch).  (b) proves e in C[x2]
#   on the slice -- the full Corollary for n = 2 -- and implies (a).
# All arithmetic exact; fail-closed.
# ============================================================================

import itertools
import sys
import time
import sympy as sp

T0 = time.time()
x1, x2 = X = sp.symbols('x1 x2')
zz = sp.Symbol('zz')
FAILS = []


def check(name, cond):
    print(f'   {"PASS" if cond else "*** FAIL ***"}  {name}', flush=True)
    if not cond:
        FAILS.append(name)


def hess(e, vs=X):
    return sp.Matrix([[sp.diff(e, a, b) for b in vs] for a in vs])


def Bof(e, vs=X):
    g = sp.Matrix([sp.diff(e, a) for a in vs])
    return sp.expand((g.T*hess(e, vs).adjugate()*g)[0, 0])


def dethess(e, vs=X):
    return sp.expand(hess(e, vs).det())


def coeffs(expr, vs=X):
    return [sp.expand(c) for c in sp.Poly(expr, *vs).coeffs()] if sp.expand(expr) != 0 else []


# ---------------------------------------------------------------- (N1)
print('(N1) affine covariance of B and det Hess (fully symbolic, generic cubic)')
mons3 = []
for k in range(1, 4):
    mons3 += sorted({sp.prod(c) for c in itertools.combinations_with_replacement(X, k)}, key=str)
c3 = sp.symbols(f'c0:{len(mons3)}')
e3 = sum(c*m for c, m in zip(c3, mons3))
a11, a12, a21, a22, u1, u2 = sp.symbols('a11 a12 a21 a22 u1 u2')
Amat = sp.Matrix([[a11, a12], [a21, a22]])
y1 = a11*x1 + a12*x2 + u1
y2 = a21*x1 + a22*x2 + u2
eA = sp.expand(e3.subs({x1: y1, x2: y2}, simultaneous=True))
B_e = Bof(e3)
B_eA = Bof(eA)
check('B(e o A) == det(A)^2 * B(e) o A  (A affine, generic)',
      sp.expand(B_eA - Amat.det()**2 * B_e.subs({x1: y1, x2: y2}, simultaneous=True)) == 0)
D_e = dethess(e3)
D_eA = dethess(eA)
check('det Hess(e o A) == det(A)^2 * det Hess(e) o A  (A affine, generic)',
      sp.expand(D_eA - Amat.det()**2 * D_e.subs({x1: y1, x2: y2}, simultaneous=True)) == 0)
lam = sp.Symbol('lam')
# n = 2: adj(lam H) = lam adj(H), so B(lam e) = lam^3 B(e) (in general lam^{n+1})
check('B(lam e) == lam^3 B(e), det Hess(lam e) == lam^2 det Hess(e), constant term irrelevant',
      sp.expand(Bof(lam*e3 + 7) - lam**3*B_e) == 0 and
      sp.expand(dethess(lam*e3 + 7) - lam**2*D_e) == 0)

# ---------------------------------------------------------------- (N2),(N3)
print()
print('(N2),(N3) top form: Identity E and the binary zero-Hessian lemma, d = 2..5')
for d in range(2, 6):
    t0 = time.time()
    bs = sp.symbols(f'b0:{d+1}')
    f = sum(bs[j]*sp.binomial(d, j)*x1**(d-j)*x2**j for j in range(d+1))   # binomial coords
    Bf = Bof(f)
    Df = dethess(f)
    check(f'd={d}: Identity E  B(f) == d/(d-1) * f * det Hess f  (generic binary form)',
          sp.expand(Bf - sp.Rational(d, d-1)*f*Df) == 0)
    # generic e of degree d: top-degree part of B(e) is B(e_d)
    mons_low = []
    for k in range(1, d):
        mons_low += sorted({sp.prod(c) for c in itertools.combinations_with_replacement(X, k)}, key=str)
    lows = sp.symbols(f'l0:{len(mons_low)}')
    e_full = f + sum(c*m for c, m in zip(lows, mons_low))
    Bfull = Bof(e_full)
    topdeg = 2*(d-1) + (d-2)          # n = 2: deg g = d-1, deg adj(H) entries = d-2
    top = sum(t for t in sp.Add.make_args(Bfull) if sp.Poly(t, *X).total_degree() == topdeg)
    check(f'd={d}: [B(e)]_top (degree {topdeg}) == B(e_d) for generic e with all lower terms',
          sp.expand(top - Bf) == 0 and sp.Poly(Bfull, *X).total_degree() <= topdeg)
    # zero-Hessian binary forms are d-th powers: Hankel 2x2 minors in rad(Hess ideal)
    Heqs = coeffs(Df)
    G = sp.groebner(Heqs, *bs, order='grevlex')
    hank = sp.Matrix([[bs[j] for j in range(d)], [bs[j+1] for j in range(d)]])
    minors = [sp.expand(hank[0, i]*hank[1, j] - hank[0, j]*hank[1, i])
              for i in range(d) for j in range(i+1, d)]
    ok = True
    for mnr in minors:
        done = False
        acc = sp.Integer(1)
        for N in range(1, 4):
            acc = sp.expand(acc*mnr)
            if G.reduce(acc)[1] == 0:
                done = True
                break
        if not done:
            GR = sp.groebner(Heqs + [1 - zz*mnr], *(list(bs) + [zz]), order='grevlex')
            done = list(GR.exprs) == [sp.Integer(1)]
        ok = ok and done
    check(f'd={d}: det Hess(f) == 0 ==> Hankel rank 1 ==> f = c*l^d  '
          f'({len(minors)} minors in radical)  [{time.time()-t0:.1f}s]', ok)

# ---------------------------------------------------------------- decision
print()
print('DECISION on the complete slice (S_d): e = x2^d + all monomials of degree 1..d-1')
for d in range(2, 6):
    t0 = time.time()
    mons = []
    for k in range(1, d):
        mons += sorted({sp.prod(c) for c in itertools.combinations_with_replacement(X, k)}, key=str)
    cs = sp.symbols(f'c{d}_0:{len(mons)}')
    e = x2**d + sum(c*m for c, m in zip(cs, mons))
    Beqs = coeffs(Bof(e))
    Deqs = coeffs(dethess(e))
    x1coeffs = [c for c, m in zip(cs, mons) if m.has(x1)]
    print(f' d={d}: {len(cs)} unknowns, {len(Beqs)} equations from B==0, '
          f'{len(Deqs)} det-Hess coefficients, {len(x1coeffs)} x1-coefficients of e')
    G = sp.groebner(Beqs, *cs, order='grevlex')
    print(f'   Groebner basis: {len(G.exprs)} elements  [{time.time()-t0:.1f}s]', flush=True)

    def in_radical(q):
        acc = sp.Integer(1)
        for N in range(1, 5):
            acc = sp.expand(acc*q)
            if G.reduce(acc)[1] == 0:
                return f'q^{N} in I'
        GR = sp.groebner(Beqs + [1 - zz*q], *(list(cs) + [zz]), order='grevlex')
        return 'Rabinowitsch' if list(GR.exprs) == [sp.Integer(1)] else None

    res_x1 = [in_radical(q) for q in x1coeffs]
    check(f'd={d}: every x1-coefficient of e lies in rad(I_d)  =>  e in C[x2] on (S_d)  '
          f'[{time.time()-t0:.1f}s]', all(r is not None for r in res_x1))
    res_D = [in_radical(q) for q in Deqs if sp.expand(q) != 0]
    check(f'd={d}: every coefficient of det Hess e lies in rad(I_d)  =>  det Hess == 0  '
          f'[{time.time()-t0:.1f}s]', all(r is not None for r in res_D))
    # positive control: the slice does contain the solutions P(x2)
    ps = sp.symbols(f'p1:{d}')
    ectrl = x2**d + sum(ps[k-1]*x2**k for k in range(1, d))
    check(f'd={d}: control: e = x2^d + P(x2) has B == 0 and det Hess == 0',
          Bof(ectrl) == 0 and dethess(ectrl) == 0)

print()
print(f'total {time.time()-T0:.1f}s')
if FAILS:
    print('FAILED:', FAILS)
    sys.exit(1)
print('THEOREM G in n = 2 DECIDED for all polynomials of degree <= 5 (linear terms')
print('included): B == 0 forces e in C[l] for a linear form l, hence det Hess == 0.')
sys.exit(0)
