# ============================================================================
# pzG_n2_decision.py -- THEOREM G in TWO variables: complete exact decision
# over the FULL coefficient space INCLUDING LINEAR TERMS, degrees 2..4
# (degree 5 in pzG_n2_deg5.py). Agent key pzG (independent second party).
#
# WHY THIS SCRIPT EXISTS. The project's theorem_G_n2_elementary.py claims an
# "exhaustive exact search over ALL polynomials of degree <= 5" but its ansatz
# drops constant AND LINEAR terms with the comment "constants and linear terms
# do not affect Hess". Constants are indeed irrelevant, but B(e) depends on
# grad e, hence ON THE LINEAR TERMS: B(x1^2/2 + x2) = 1 while B(x1^2/2) = 0.
# Linear terms cannot in general be removed by affine changes (translations
# shift grad e by evaluation, not by an arbitrary constant). So that scan,
# while correct in what it checked, was NOT exhaustive as claimed. This script
# performs the genuinely full-coefficient-space decision (all monomials of
# degree 1..d; the constant term provably never enters B or det Hess).
#
# STATEMENT DECIDED. For e in C[x1,x2] of degree <= d (d = 2,3,4):
#     B(e) == 0  ==>  det Hess e == 0,
# certified by radical membership: every coefficient (in x) of det Hess e lies
# in the radical of the ideal generated by the coefficients of B(e), over the
# polynomial ring in ALL of e's coefficients. Method: Groebner basis of the
# B-coefficient ideal, then for each det-coefficient D_k try direct reduction
# of D_k^N (N = 1..3) and fall back to a Rabinowitsch certificate
# (1 in <Beqs, 1 - z*D_k>). Fail-closed: any failure aborts with nonzero exit.
#
# CONTEXT. The n = 2 case also has a complete HAND proof for all degrees
# (level curves of e are forced straight; a smooth generic fibre is a union
# of PARALLEL lines since non-parallel complex lines meet in a critical point
# of e which a generic fibre avoids; comparing two generic fibres forces
# e in C[L], so Hess e = phi''(L) vv^T has det == 0). NOTE the original
# header's appeal to "reducedness" of the generic fibre is not enough -- two
# crossing lines form a reduced but singular curve; the correct fact is that
# a generic fibre avoids the (finitely many) critical VALUES of e, hence is
# smooth, hence its line components are pairwise disjoint = parallel.
# This script is the machine counterpart in low degree.
# ============================================================================

import itertools
import sys
import time
import sympy as sp

x1, x2 = X = sp.symbols('x1 x2')
zz = sp.Symbol('zz')


def hess(e):
    return sp.Matrix([[sp.diff(e, a, b) for b in X] for a in X])


def Bof(e):
    g = sp.Matrix([sp.diff(e, a) for a in X])
    return sp.expand((g.T*hess(e).adjugate()*g)[0, 0])


overall_start = time.time()
for d in (2, 3, 4):
    t0 = time.time()
    mons = []
    for k in range(1, d+1):                      # degree 1..d: LINEAR TERMS IN
        mons += sorted({sp.prod(c) for c in
                        itertools.combinations_with_replacement(X, k)}, key=str)
    cs = sp.symbols(f'c{d}_0:{len(mons)}')
    e = sum(c*m for c, m in zip(cs, mons))
    Bx = Bof(e)
    Beqs = [sp.expand(t) for t in sp.Poly(Bx, *X).coeffs()] if Bx != 0 else []
    Dx = sp.expand(hess(e).det())
    Deqs = [sp.expand(t) for t in sp.Poly(Dx, *X).coeffs()] if Dx != 0 else []
    print(f'degree {d}: {len(cs)} coefficients (incl. linear), '
          f'{len(Beqs)} equations from B==0, {len(Deqs)} det-Hess coefficients')
    G = sp.groebner(Beqs, *cs, order='grevlex')
    print(f'  Groebner basis of the B-ideal: {len(G.exprs)} elements '
          f'({time.time()-t0:.1f}s)')
    n_direct, n_rab = 0, 0
    for Dk in Deqs:
        if sp.expand(Dk) == 0:
            continue
        done = False
        acc = sp.Integer(1)
        for N in (1, 2, 3):
            acc = sp.expand(acc*Dk)
            if G.reduce(acc)[1] == 0:            # Dk^N in ideal => Dk in radical
                done = True
                n_direct += 1
                break
        if not done:
            GR = sp.groebner(Beqs + [1 - zz*Dk], *(list(cs) + [zz]),
                             order='grevlex')
            assert list(GR.exprs) == [sp.Integer(1)], \
                f'THEOREM G REFUTED at degree {d}: det-coefficient {Dk} does ' \
                f'not vanish on V(B)'
            n_rab += 1
    print(f'  radical membership: {n_direct} by direct power reduction, '
          f'{n_rab} by Rabinowitsch -- ALL PASS ({time.time()-t0:.1f}s)')

print()
print(f'TOTAL {time.time()-overall_start:.1f}s.')
print('THEOREM G in n = 2 CONFIRMED over the FULL coefficient space (linear')
print('terms included) in degrees 2, 3, 4: every polynomial solution of')
print('B == 0 has det Hess == 0. Combined with the corrected hand proof')
print('(header), the two-variable case is settled completely in all degrees.')
sys.exit(0)
