# vgc_consequences.py -- key: vgc  (Verify G-Consequences: independent pass)
#
# Independent re-verification of "consequences of Theorem G beyond HC_4",
# written without reusing the code of the earlier tgc/gcv/litG certificates.
# Exact arithmetic only; every check is a fail-closed assert.  A check marked
# PROOF is a polynomial identity in FREE symbols (jet entries or generic
# coefficients) and therefore settles every instance of the stated shape;
# checks marked INSTANCE are exact witnesses / consistency checks.
#
# NOTATION.  B(e) := grad(e)^T adj(Hess e) grad(e);  E := degree-d
# homogenization of e in x0;  H := Hess e, g := grad e, D := det H.
#
# THEOREM G (project):  B(e) == 0  ==>  det Hess e == 0   (e in C[x1..xn]).
#
# ---------------------------------------------------------------------------
# A.  THREE EQUIVALENT FORMS OF THE HYPOTHESIS  B(e) == 0   (all PROOF)
# ---------------------------------------------------------------------------
# A1  det[[H, g],[g^T, 0]] = -B          (Cauchy bordered expansion)
# A2  det Hess_{n+1}( y*e(x) + f(x) ) = -g^T adj(y H_e + H_f) g  is a
#     polynomial of degree <= n-1 in y whose y^{n-1}-coefficient is -B(e);
#     with f = 0 it is exactly -y^{n-1} B(e).  Hence
#         THEOREM G  <==>  [ det Hess_{n+1}(y*e(x)) == 0  ==>  det Hess_n e == 0 ],
#     and (Corollary LV) det Hess_{n+1}(y e + f) == 0 forces det Hess_n e == 0.
# A3  (NEW HERE: algebraic-dependence form.)  With the row vectors
#         J' := [ g_n H_i - g_i H_n  (i < n) ;  g^T ]      (H_i = i-th row of H)
#     one has   det J' = g_n^{n-2} * B(e).   Since the rows of J' are, up to
#     the factor g_n^2, the gradients of the ratios r_i = g_i/g_n together
#     with grad e, this says:
#         B(e) == 0  <==>  the map  Psi = (e, [grad e]) : C^n --> C x P^{n-1}
#                          has rank <= n-1 everywhere  (is not dominant)
#                    <==>  e is algebraically dependent on the ratios
#                          d_1e/d_ne, ..., d_{n-1}e/d_ne.
#     Theorem G therefore reads: "if a polynomial is algebraic over the field
#     generated by the RATIOS of its partial derivatives, then its partial
#     derivatives themselves are algebraically dependent" -- the exact
#     inhomogeneous analogue of Hesse's observation that det Hess == 0 iff the
#     partials are algebraically dependent.
# A4  Dolgachev's affine equation of the Hessian (CAG (1.20)-(1.21)):
#         det Hess_{n+1}(E)|_{x0=1} = d(d-1) e det Hess_n e - (d-1)^2 B(e),
#     and its pencil version with a free parameter c:
#         det Hess_{n+1}(E - c x0^d)|_{x0=1} = d(d-1)(e-c) det Hess_n e - (d-1)^2 B(e).
#     Consequences (with Theorem G):
#         B(e) == 0  <==>  det Hess_n e == 0  AND  det Hess_{n+1} E == 0;
#     the projective closure X_c of {e = c} is developable (Hessian vanishes
#     on X_c; for reduced F_c this is degeneracy of the Gauss map, Segre/Zak,
#     Dolgachev Thm 1.1.20) iff (e-c) | B(e); infinitely many such c force
#     B == 0 (the e-c are pairwise coprime), whence by Theorem G EVERY member
#     of the pencil <E, x0^d> has identically vanishing Hessian.
# A5  The converse of Theorem G holds exactly on the class {det Hess_{n+1}E == 0}:
#     there B(e) = (d/(d-1)) e det Hess_n e (from A4), so B == 0 <=> D == 0.
#     For n+1 <= 4 (Gordan-Noether) this class is {translates of homogeneous
#     polynomials} U {affinely (n-1)-variable}; for n+1 >= 5 it is larger
#     (Perazzo).  Off this class the converse fails (x1^2/2 + x2).  INSTANCES.
#
# ---------------------------------------------------------------------------
# B.  THE de BONDT-van den ESSEN FAMILY  h = sum_i g_i(l) x_i,  l = a.x
# ---------------------------------------------------------------------------
# The task asked to verify that this family "always has B != 0".  That is
# FALSE as literally stated (h = x1 x2 + x1 x3 = x1(x2+x3) is a member with
# g = (0, l, l), a = e1, and B(h) == 0).  The TRUE statement, proved here for
# ALL degrees and ALL a:
#     (B-closed form)   B(h) = -( det[ a | g(l) | g'(l) ] )^2 ,
#     (B-criterion)     B(h) == 0  <==>  h is affinely 2-variable,
# and in particular every member with three essential variables has B != 0,
# which is all the n = 3 chain needs.
# Proof.  Chain rule: grad h = g + (g'.x) a,  Hess h = a v^T + v a^T + mu a a^T
# with v = g'(l), mu = g''(l).x  [elementary; machine-checked generically for
# deg g_i <= 3 and symbolic a].  Matrix identity for FREE a, v in C^3, mu in C:
#     adj(a v^T + v a^T + mu a a^T) = -(a x v)(a x v)^T        (PROOF, B2)
# hence B(h) = -( (g + (g'.x)a) . (a x g') )^2 = -( det[a, g', g] )^2.
# Criterion: put u(l) := a x g(l) in C[l]^3.  If u == 0 then g = phi(l) a and
# h = phi(l) l is 1-variable.  Otherwise the identity
#     (a x b) x (a x c) = det[a,b,c] a                           (PROOF, B4)
# gives u x u' = det[a,g,g'] a, so B(h) == 0 iff u x u' == 0 iff all 2x2
# Wronskians of the components of u vanish iff (char 0) u(l) = c(l) u0 for a
# constant u0 != 0, iff g(l) lies in the fixed 2-plane {w : a x w in C u0} =
# span(a, w0) for all l, i.e. g = alpha(l) a + beta(l) w0 and
# h = alpha(l) l + beta(l) (w0.x) in C[l, w0.x]: linearly 2-variable.
# Conversely an affinely 2-variable h has B == 0 (adj(Hess) has a single
# nonzero entry, in the direction the gradient misses).  [Wronskian step
# machine-checked on instances (B5); end-to-end exact sweep (B6).]
#
# ---------------------------------------------------------------------------
# C.  THE n = 3 CHAIN WITHOUT THEOREM F
# ---------------------------------------------------------------------------
#   B(e) == 0 =(G)=> det Hess_3 e == 0 =(de Bondt's thesis Prop. 5.3.1, read
#   verbatim from lit/debondt-thesis/homokema.txt l.6521-6531; = dBvdE,
#   Singular Hessians, J. Algebra 282 (2004))=> after a LINEAR change
#       (A) e = a(x1,x2) + lam x3        or     (B) e = a1(x1) + a2(x1)x2 + a3(x1)x3
#   (both shapes absorb linear terms, so "reduced" hypotheses are harmless).
#   (A): B = lam^2 det Hess_2 a (PROOF, C1); B == 0 => lam = 0 or det Hess_2 a
#        == 0 => a = phi(l) + linear (Hesse's theorem in dimension two for
#        non-homogeneous polynomials without linear terms, de Bondt
#        arXiv:1501.05168 Sec. "Hesse's theorem") => e in C[l, m] for a
#        second linear form m.
#   (B): B = -(a2 a3' - a3 a2')^2 (PROOF, C2); B == 0 => a2, a3 C-dependent
#        => D_v e == 0 for v = (0, c3, -c2) != 0.
#
# ---------------------------------------------------------------------------
# D.  HOMOGENEOUS CONVERSE AND THE NAGAOKA-YAZAWA ATTRIBUTION
# ---------------------------------------------------------------------------
#   Identity E:  g^T adj(H) g = (d/(d-1)) e det H for e homogeneous (PROOF for
#   ternary d = 2,3 and binary d = 2..5); Nagaoka-Yazawa arXiv:1904.01800
#   Prop. 2.3 (label identity1; numbering verified from the TeX source:
#   \newtheorem{thm}{..}[section], shared counter, Lemma 2.1, Lemma 2.2,
#   Proposition 2.3 in Section 2) is  det(-F H + s g g^T) =
#   (-1)^{n-1} (r/(r-1)) (s - (r-1)/r) F^n det H, and its s^1-coefficient is
#   (-1)^{n-1} F^{n-1} * (Identity E)  (PROOF).  On cones B == 0 <=> D == 0.
#
# ---------------------------------------------------------------------------
# E.  LEFSCHETZ DICTIONARY (translation only, no new theorem)
# ---------------------------------------------------------------------------
#   Maeno-Watanabe / Watanabe Hessian criterion: for a form F of degree r
#   whose partials are linearly independent, L_a = a.x satisfies the strong
#   Lefschetz property at degree 1 in A_F iff det H_F(a) != 0; the Gram matrix
#   of the pairing (x_i, x_j) -> [x_i L_a^{r-2} x_j] is (r-2)! H_F(a) (checked,
#   E1).  So the pencil form of Theorem G says: if for infinitely many c every
#   point of V(E - c x0^d) is a non-Lefschetz point of A_{E - c x0^d} at degree
#   one, then NO member of the pencil has a Lefschetz element at degree one.
#   For n <= 3 this is vacuous (B == 0 forces a cone); the smallest honest
#   instance is the dehomogenized Perazzo cubic (E2).

import itertools
import random
import sympy as sp

random.seed(20260825)

x0, y, c, s = sp.symbols('x0 y c s')
X = {n: sp.symbols(f'x1:{n+1}') for n in (2, 3, 4, 5)}
x1, x2, x3, x4, x5 = X[5]


def hess(e, vs):
    return sp.Matrix([[sp.diff(e, a, b) for b in vs] for a in vs])


def grad(e, vs):
    return sp.Matrix([sp.diff(e, a) for a in vs])


def Bof(e, vs):
    H = hess(e, vs)
    g = grad(e, vs)
    return sp.expand((g.T * H.adjugate() * g)[0, 0])


def dethess(e, vs):
    return sp.expand(hess(e, vs).det(method='berkowitz'))


def ess_vars(e, vs):
    """number of essential variables = n - dim{v : D_v e == 0}"""
    n = len(vs)
    cs = sp.symbols(f'k0:{n}')
    Dv = sp.expand(sum(ci * sp.diff(e, xi) for ci, xi in zip(cs, vs)))
    if Dv == 0:
        return 0
    eqs = sp.Poly(Dv, *vs).coeffs()
    M, _ = sp.linear_eq_to_matrix(eqs, cs)
    return n - len(M.nullspace())


def homog(e, vs, d):
    P = sp.Poly(e, *vs)
    return sp.expand(sum(co * sp.prod([v**k for v, k in zip(vs, mono)]) * x0**(d - sum(mono))
                         for mono, co in zip(P.monoms(), P.coeffs())))


def symH(n, tag):
    M = sp.zeros(n, n)
    for i in range(n):
        for j in range(i, n):
            M[i, j] = M[j, i] = sp.Symbol(f'{tag}{i}{j}')
    return M


def gen_poly(vs, deg, tag, homogeneous=False, min_deg=0):
    degs = [deg] if homogeneous else range(min_deg, deg + 1)
    mons = [m for k in degs for m in sorted({sp.prod(cc) for cc in
            itertools.combinations_with_replacement(vs, k)}, key=str)]
    cs = sp.symbols(f'{tag}0:{len(mons)}')
    return sum(ci * m for ci, m in zip(cs, mons))


def rand_poly(vs, deg, lo=-3, hi=3):
    mons = [m for k in range(0, deg + 1) for m in
            {sp.prod(cc) for cc in itertools.combinations_with_replacement(vs, k)}]
    return sp.expand(sum(sp.Integer(random.randint(lo, hi)) * m for m in mons))


def banner(t):
    print()
    print('=' * 76)
    print(t)
    print('=' * 76)


# ======================================================================
banner('A1  det[[H,g],[g^T,0]] = -g^T adj(H) g            n = 2,3,4   (PROOF)')
for n in (2, 3, 4):
    H = symH(n, f'h{n}_')
    g = sp.Matrix(sp.symbols(f'g{n}_0:{n}'))
    M = sp.zeros(n + 1, n + 1)
    M[:n, :n] = H
    M[:n, n] = g
    M[n, :n] = g.T
    assert sp.expand(M.det(method='berkowitz') + (g.T * H.adjugate() * g)[0, 0]) == 0
    print(f'  n={n}: PROVED')

banner('A2  det Hess_{n+1}(y e + f): degree <= n-1 in y, top coefficient -B(e)   (PROOF)')
for n in (2, 3):
    He, Hf = symH(n, f'p{n}_'), symH(n, f'q{n}_')
    g = sp.Matrix(sp.symbols(f'r{n}_0:{n}'))
    M = sp.zeros(n + 1, n + 1)
    M[:n, :n] = y * He + Hf
    M[:n, n] = g
    M[n, :n] = g.T
    D = sp.expand(M.det(method='berkowitz'))
    assert sp.expand(D + (g.T * (y * He + Hf).adjugate() * g)[0, 0]) == 0
    P = sp.Poly(D, y)
    assert P.degree() <= n - 1
    assert sp.expand(P.coeff_monomial(y**(n - 1)) + (g.T * He.adjugate() * g)[0, 0]) == 0
    print(f'  n={n}: det Hess(y e + f) = -g^T adj(yH_e + H_f) g, [y^(n-1)] = -B(e)   PROVED')
for n in (2, 3, 4):
    H = symH(n, f'u{n}_')
    g = sp.Matrix(sp.symbols(f'w{n}_0:{n}'))
    M = sp.zeros(n + 1, n + 1)
    M[:n, :n] = y * H
    M[:n, n] = g
    M[n, :n] = g.T
    assert sp.expand(M.det(method='berkowitz') + y**(n - 1) * (g.T * H.adjugate() * g)[0, 0]) == 0
    print(f'  n={n}: det Hess_(n+1)(y e(x)) = -y^(n-1) B(e)                          PROVED')
print('  => Theorem G <=> [det Hess(y e(x)) == 0 => det Hess e == 0]; Corollary LV.')

banner("A3  Jacobian of (e, [grad e]):  det J' = g_n^(n-2) B(e)     n = 2,3,4   (PROOF)")
for n in (2, 3, 4):
    H = symH(n, f'a{n}_')
    g = sp.Matrix(sp.symbols(f'b{n}_0:{n}'))
    rows = []
    for i in range(n - 1):
        rows.append([g[n - 1] * H[i, j] - g[i] * H[n - 1, j] for j in range(n)])
    rows.append([g[j] for j in range(n)])
    Jp = sp.Matrix(rows)
    B = sp.expand((g.T * H.adjugate() * g)[0, 0])
    assert sp.expand(Jp.det(method='berkowitz') - g[n - 1]**(n - 2) * B) == 0, n
    print(f'  n={n}: det[ g_n H_i - g_i H_n (i<n) ; g^T ] = g_n^(n-2) * B          PROVED')
# polynomial-level confirmation on an instance: rank of Jac(e, g1/g3, g2/g3)
e_i = x1**3 + x1 * x2 * x3 + x2**2 + x3 + 2 * x1
gi = grad(e_i, X[3])
ratios = [gi[0] / gi[2], gi[1] / gi[2]]
Jpsi = sp.Matrix([[sp.diff(fn, v) for v in X[3]] for fn in [e_i] + ratios])
dJ = sp.simplify(Jpsi.det())
assert sp.simplify(dJ - (-1)**(3 - 1) * Bof(e_i, X[3]) / gi[2]**3) == 0
print('  instance n=3: det Jac(e, g1/g3, g2/g3) = (-1)^(n-1) B / g_3^n            PASS')
print('  => B(e) == 0 <=> (e,[grad e]) not dominant <=> e algebraic over C(g_i/g_n).')

banner('A4  Dolgachev affine equation of the Hessian + pencil version   (PROOF)')
for (n, d) in ((2, 2), (2, 3), (2, 4), (3, 2), (3, 3)):
    vs = X[n]
    e = gen_poly(vs, d, f'e{n}{d}_')
    E = homog(e, vs, d)
    lhs = sp.expand(dethess(E, (x0,) + tuple(vs)).subs(x0, 1))
    rhs = sp.expand(d * (d - 1) * e * dethess(e, vs) - (d - 1)**2 * Bof(e, vs))
    assert sp.expand(lhs - rhs) == 0, (n, d)
    # pencil version with a free c
    Ec = sp.expand(E - c * x0**d)
    lhs_c = sp.expand(dethess(Ec, (x0,) + tuple(vs)).subs(x0, 1))
    rhs_c = sp.expand(d * (d - 1) * (e - c) * dethess(e, vs) - (d - 1)**2 * Bof(e, vs))
    assert sp.expand(lhs_c - rhs_c) == 0, (n, d, 'pencil')
    print(f'  n={n}, d={d}: identity and pencil identity (free c)                  PROVED')
print('  => X_c developable <=> (e - c) | B(e);  infinitely many c => B == 0 (coprime')
print('     factors, bounded degree) => (Thm G) every pencil member has Hess == 0.')
# the coprimality/degree step on a witness with B != 0: (e-c) | B for no c
hb = x1 * x2 + x1**2 * x3
Bb = Bof(hb, X[3])
assert Bb == -x1**4
assert all(sp.rem(sp.Poly(Bb, *X[3]), sp.Poly(hb - cc, *X[3])).as_expr() != 0 for cc in range(-3, 4))
print('  witness x1x2 + x1^2x3: B = -x1^4 is divisible by no e - c            PASS')

banner('A5  converse of G holds on {det Hess_{n+1} E == 0}, fails off it   (INSTANCES)')
# translated homogeneous: e = G(1 - x1, x2, x3), E = G(x0 - x1, x2, x3) a cone
yy = sp.symbols('y1:4')
G = yy[0]**3 + yy[1]**3 + yy[2]**3 + yy[0] * yy[1] * yy[2]
e_t = sp.expand(G.subs({yy[0]: 1 - x1, yy[1]: x2, yy[2]: x3}, simultaneous=True))
E_t = homog(e_t, X[3], 3)
assert dethess(E_t, (x0,) + X[3]) == 0
De, Be = dethess(e_t, X[3]), Bof(e_t, X[3])
assert De != 0 and Be != 0 and sp.expand(Be - sp.Rational(3, 2) * e_t * De) == 0
print('  e = G(1-x1,x2,x3), G a nondegenerate cubic: det Hess_4 E == 0, and')
print('     B = (3/2) e det Hess_3 e with both sides nonzero (converse holds)   PASS')
# dehomogenized Perazzo: both vanish
e_p = x2 + x1 * x3 + x1**2 * x4
E_p = homog(e_p, X[4], 3)
assert sp.expand(E_p - (x0**2 * x2 + x0 * x1 * x3 + x1**2 * x4)) == 0
assert dethess(E_p, (x0,) + X[4]) == 0 and Bof(e_p, X[4]) == 0 and dethess(e_p, X[4]) == 0
assert ess_vars(e_p, X[4]) == 4
print('  e = x2 + x1x3 + x1^2x4 (Perazzo dehomogenized): B = D = 0, det Hess_5 E = 0,')
print('     4 essential variables -- Corollary E fails for n = 4               PASS')
# off the class: converse fails
e_f = x1**2 / 2 + x2
assert dethess(e_f, X[2]) == 0 and Bof(e_f, X[2]) == 1
assert dethess(homog(e_f, X[2], 2), (x0,) + X[2]) != 0
print('  e = x1^2/2 + x2: D = 0, B = 1, det Hess_3 E = -1 != 0 (converse fails)  PASS')

# ======================================================================
banner('B1  chain rule for h = sum g_i(l) x_i, l = a.x  (generic deg <= 3, symbolic a)')
a = sp.Matrix(sp.symbols('a1:4'))
l = (a.T * sp.Matrix(X[3]))[0, 0]
L = sp.Symbol('L')
gL = [gen_poly((L,), 3, f'g{i}_') for i in range(3)]
gl = sp.Matrix([gi.subs(L, l) for gi in gL])
gpl = sp.Matrix([sp.diff(gi, L).subs(L, l) for gi in gL])
gppl = sp.Matrix([sp.diff(gi, L, 2).subs(L, l) for gi in gL])
xv = sp.Matrix(X[3])
h = sp.expand((gl.T * xv)[0, 0])
w_pred = gl + (gpl.T * xv)[0, 0] * a
H_pred = a * gpl.T + gpl * a.T + (gppl.T * xv)[0, 0] * a * a.T
assert sp.expand(grad(h, X[3]) - w_pred) == sp.zeros(3, 1)
assert sp.expand(hess(h, X[3]) - H_pred) == sp.zeros(3, 3)
print("  grad h = g + (g'.x) a,   Hess h = a g'^T + g' a^T + (g''.x) a a^T        PASS")

banner('B2  adj(a v^T + v a^T + mu a a^T) = -(a x v)(a x v)^T   free a,v,mu   (PROOF)')
av = sp.Matrix(sp.symbols('A1:4'))
vv = sp.Matrix(sp.symbols('V1:4'))
mu = sp.Symbol('mu')
Msym = av * vv.T + vv * av.T + mu * av * av.T
cr = av.cross(vv)
assert sp.expand(Msym.adjugate() + cr * cr.T) == sp.zeros(3, 3)
assert sp.expand(Msym.det()) == 0
print('  PROVED (7 free symbols).  Hence w^T adj(.) w = -(w.(a x v))^2 = -det[a,v,w]^2.')

banner("B3  closed form  B(h) = -det[a | g(l) | g'(l)]^2   (generic deg <= 3, symbolic a)")
Bh = Bof(h, X[3])
detag = sp.Matrix.hstack(a, gl, gpl).det()
assert sp.expand(Bh + detag**2) == 0
assert dethess(h, X[3]) == 0
print("  B(h) = -det[a,g,g']^2 and det Hess h == 0, generic g_i of deg <= 3      PASS")
print('  (degree-free proof: B1 chain rule + B2 matrix identity + column operation')
print("   det[a, g', g + (g'.x)a] = det[a, g', g].)")

banner('B4  (a x b) x (a x c) = det[a,b,c] a     free symbols   (PROOF)')
bb = sp.Matrix(sp.symbols('B1:4'))
cc_ = sp.Matrix(sp.symbols('C1:4'))
lhs = (av.cross(bb)).cross(av.cross(cc_))
rhs = sp.Matrix.hstack(av, bb, cc_).det() * av
assert sp.expand(lhs - rhs) == sp.zeros(3, 1)
print("  PROVED.  With u = a x g:  u x u' = det[a,g,g'] a.")

banner("B5  Wronskian step: u x u' == 0  <=>  u(l) = c(l) u0  (rank of coefficient matrix <= 1)")
ok = 0
for trial in range(40):
    deg = random.randint(0, 6)
    if trial % 2 == 0:
        u0 = sp.Matrix([random.randint(-3, 3) for _ in range(3)])
        cl = rand_poly((L,), deg)
        u = cl * u0
    else:
        u = sp.Matrix([rand_poly((L,), deg) for _ in range(3)])
    u = u.applyfunc(sp.expand)
    up = u.applyfunc(lambda t: sp.diff(t, L))
    wz = (u.cross(up)).applyfunc(sp.expand) == sp.zeros(3, 1)
    # coefficient matrix 3 x (deg+1)
    Cm = sp.Matrix([[sp.Poly(ui, L).coeff_monomial(L**k) for k in range(deg + 1)] for ui in u])
    rank1 = (Cm.rank() <= 1)
    assert wz == rank1, (u, wz, rank1)
    ok += 1
print(f"  {ok} exact instances: u x u' == 0  <=>  rank(coeff matrix) <= 1          PASS")

banner('B6  END-TO-END SWEEP over the family (all a, degrees <= 4, translations)')
# (degree <= 4 keeps the run under the environment's ten-minute budget: a
#  member of degree 7 has B of degree 22 in three variables; a first attempt
#  with degrees <= 6 died without a traceback, exit code 1, at ~7 minutes.)
Ivec = sp.I
special_a = [sp.Matrix([1, 0, 0]), sp.Matrix([1, 1, 0]), sp.Matrix([1, Ivec, 0]),   # isotropic
             sp.Matrix([2, -1, 3]), sp.Matrix([0, 0, 1]), sp.Matrix([1, Ivec, 1])]
cnt = {'B0_2var': 0, 'Bnz_3var': 0}
NTRIALS = 30
for trial in range(NTRIALS):
    if trial < len(special_a):
        av_ = special_a[trial]
    else:
        av_ = sp.Matrix([random.randint(-3, 3) for _ in range(3)])
        if av_ == sp.zeros(3, 1):
            av_ = sp.Matrix([1, 0, 0])
    l_ = (av_.T * xv)[0, 0]
    deg = random.randint(0, 4)
    print(f'    trial {trial:2d}: a = {list(av_)}, deg = {deg}, mode = {trial % 3}', flush=True)
    mode = trial % 3
    if mode == 0:            # forced degenerate: g in span(a, w0)
        w0 = sp.Matrix([random.randint(-3, 3) for _ in range(3)])
        gL_ = (rand_poly((L,), deg) * av_ + rand_poly((L,), deg) * w0).applyfunc(sp.expand)
    else:
        gL_ = sp.Matrix([rand_poly((L,), deg) for _ in range(3)])
    g_ = gL_.subs(L, l_)
    gp_ = gL_.applyfunc(lambda t: sp.diff(t, L)).subs(L, l_)
    h_ = sp.expand((g_.T * xv)[0, 0])
    # random affine translation (B, det Hess, ess_vars are translation invariant)
    tr = {v: v + random.randint(-2, 2) for v in X[3]}
    h_t = sp.expand(h_.subs(tr, simultaneous=True))
    assert dethess(h_t, X[3]) == 0, 'family member with nonzero Hessian?!'
    Bt = Bof(h_t, X[3])
    closed = sp.expand(-sp.Matrix.hstack(av_, g_, gp_).det()**2)
    assert sp.expand(Bt - closed.subs(tr, simultaneous=True)) == 0, 'closed form failed'
    nv = ess_vars(h_t, X[3])
    if Bt == 0:
        assert nv <= 2, f'B == 0 but {nv} essential variables: {h_t}'
        cnt['B0_2var'] += 1
    else:
        assert nv == 3, f'B != 0 but only {nv} essential variables: {h_t}'
        cnt['Bnz_3var'] += 1
print(f'  {NTRIALS} members (incl. isotropic a = (1,i,0), (1,i,1)): det Hess == 0 always,')
print(f"  B = -det[a,g,g']^2 always; B == 0 => <= 2 ess. vars ({cnt['B0_2var']} cases),")
print(f"  B != 0 => 3 ess. vars ({cnt['Bnz_3var']} cases).                              PASS")
# the two named witnesses
h0 = x1 * x2 + x1 * x3
assert Bof(h0, X[3]) == 0 and ess_vars(h0, X[3]) == 2 and dethess(h0, X[3]) == 0
h1 = x1 * x2 + x1**2 * x3
assert Bof(h1, X[3]) == -x1**4 and ess_vars(h1, X[3]) == 3
print('  x1x2 + x1x3 (member, g = (0,l,l)): B == 0, 2 ess. vars  -> "always B != 0" is FALSE')
print('  x1x2 + x1^2x3 (member, g = (0,l,l^2)): B = -x1^4, 3 ess. vars')

# ======================================================================
banner('C1  branch (A):  B(a(x1,x2) + lam x3) = lam^2 det Hess_2 a   (jet PROOF)')
a1s, a2s, a11, a12, a22, lam = sp.symbols('a1 a2 a11 a12 a22 lam')
HA = sp.Matrix([[a11, a12, 0], [a12, a22, 0], [0, 0, 0]])
gA = sp.Matrix([a1s, a2s, lam])
assert sp.expand((gA.T * HA.adjugate() * gA)[0, 0] - lam**2 * (a11 * a22 - a12**2)) == 0
print('  PROVED.  B == 0 => lam = 0 or det Hess_2 a == 0 (=> a = phi(l) + linear).')
# an instance of the second alternative: a = (x1+x2)^3 + x1 - x2, e = a + 5 x3
eA = (x1 + x2)**3 + x1 - x2 + 5 * x3
assert Bof(eA, X[3]) == 0 and ess_vars(eA, X[3]) == 2
print('  instance (x1+x2)^3 + x1 - x2 + 5x3: B == 0, 2 essential variables         PASS')

banner("C2  branch (B):  B(a1 + a2 x2 + a3 x3) = -(a2 a3' - a3 a2')^2   (jet PROOF)")
u_, p_, A2, A3, dA2, dA3 = sp.symbols('u p A2 A3 dA2 dA3')
HB = sp.Matrix([[p_, dA2, dA3], [dA2, 0, 0], [dA3, 0, 0]])
gB = sp.Matrix([u_, A2, A3])
assert sp.expand((gB.T * HB.adjugate() * gB)[0, 0] + (A2 * dA3 - A3 * dA2)**2) == 0
print('  PROVED.  B == 0 => W(a2,a3) == 0 => a2, a3 C-dependent (char 0) => D_v e == 0.')
for trial in range(12):
    d2, d3 = random.randint(0, 5), random.randint(0, 5)
    A2p = rand_poly((x1,), d2)
    A3p = sp.expand(random.choice([-2, 3]) * A2p) if trial % 3 == 0 else rand_poly((x1,), d3)
    A1p = rand_poly((x1,), 4)
    eB = A1p + A2p * x2 + A3p * x3
    W = sp.expand(A2p * sp.diff(A3p, x1) - A3p * sp.diff(A2p, x1))
    assert sp.expand(Bof(eB, X[3]) + W**2) == 0
    assert (W == 0) == (ess_vars(eB, X[3]) <= 2)
print('  12 exact instances: B = -W^2 and (W == 0 <=> <= 2 essential variables)   PASS')

# ======================================================================
banner('D   Identity E, Nagaoka-Yazawa Prop. 2.3, and the homogeneous converse (PROOF)')
for (n, d) in ((3, 2), (3, 3), (2, 2), (2, 3), (2, 4), (2, 5)):
    vs = X[n]
    F = gen_poly(vs, d, f'F{n}{d}_', homogeneous=True)
    H = hess(F, vs)
    g = grad(F, vs)
    dH = H.det(method='berkowitz')
    assert sp.expand((g.T * H.adjugate() * g)[0, 0] - sp.Rational(d, d - 1) * F * dH) == 0
    NYl = sp.expand((-F * H + s * g * g.T).det(method='berkowitz'))
    NYr = sp.expand((-1)**(n - 1) * sp.Rational(d, d - 1) * (s - sp.Rational(d - 1, d)) * F**n * dH)
    assert sp.expand(NYl - NYr) == 0
    assert sp.expand(sp.diff(NYl, s) - (-1)**(n - 1) * F**(n - 1) * (g.T * H.adjugate() * g)[0, 0]) == 0
    print(f'  n={n}, d={d}: Identity E; NY identity; [s^1] NY = (-1)^(n-1) F^(n-1) * Id.E   PROVED')
print('  => homogeneous e: B(e) = (d/(d-1)) e det Hess e, so B == 0 <=> det Hess e == 0.')

# ======================================================================
banner('E1  Maeno-Watanabe Gram matrix  [x_i L_a^{r-2} x_j] = (r-2)! F_ij(a)   (INSTANCE)')
vs = X[3]
F4 = x1**4 + 2 * x1**2 * x2 * x3 - x2**4 + x3**4 + x1 * x2**3 - 3 * x2 * x3**3 + x1**2 * x3**2
r = 4
apt = (1, 2, -1)


def Lop(P):
    return sum(ai * sp.diff(P, vi) for ai, vi in zip(apt, vs))   # a . nabla


Gram = sp.zeros(3, 3)
for i in range(3):
    for j in range(3):
        P = sp.diff(F4, vs[i], vs[j])
        for _ in range(r - 2):
            P = Lop(P)
        Gram[i, j] = sp.expand(P)
Hpt = hess(F4, vs).subs(dict(zip(vs, apt)))
assert Gram == sp.factorial(r - 2) * Hpt
print('  quartic ternary F, a = (1,2,-1): Gram = 2! * Hess F(a)                  PASS')
print('  => (partials independent) L_a is Lefschetz at degree 1 iff det Hess F(a) != 0.')

banner('E2  the pencil form on the Perazzo cubic (smallest non-vacuous instance)')
P5 = x0**2 * x2 + x0 * x1 * x3 + x1**2 * x4
V5 = (x0, x1, x2, x3, x4)
Pc = sp.expand(P5 - c * x0**3)
parts = [sp.diff(Pc, v) for v in V5]
mons5 = sorted({m for pp in parts for m in sp.Poly(pp, *V5).monoms()})
Cmat = sp.Matrix([[sp.Poly(pp, *V5).coeff_monomial(sp.prod([v**k for v, k in zip(V5, m)]))
                   for m in mons5] for pp in parts])
assert Cmat.rank() == 5            # partials linearly independent over C(c)
assert dethess(Pc, V5) == 0        # Hessian vanishes identically for every c
print('  P_c = Perazzo - c x0^3: 5 independent partials, det Hess_5 == 0 for free c;')
print('  hence NO linear form is a strong Lefschetz element at degree 1 for any c,')
print('  exactly as the pencil form of Theorem G predicts from B(e) == 0.         PASS')

print()
print('ALL CHECKS PASSED (vgc_consequences.py).')
